!function(){if(window.burntCookieLoaded)return void console.log("🔥 Burnt Cookie 🍪 is already loaded.");window.burntCookieLoaded=!0;const e={};function register(o,s,a){e[o.toLowerCase()]={desc:s,fn:a}}function showHelp(){console.log("🔥 Burnt Cookie 🍪 – Available commands:");for(const o of Object.keys(e))console.log(`  • ${o} — ${e[o].desc}`);console.log("  • help — show this list")}function toggle(e,o,s,a){window[e]?(clearInterval(window[e]),window[e]=null,console.log(`🛑 ${a}`)):(window[e]=setInterval(o,s),console.log(`▶️ ${a}`))}
// ─── Core Cheats ─────────────────────────────────────────
register("maxcookies","Set cookies to 1e308",(()=>{Game.cookies=1e308})),register("addcookies","Add N cookies",(([e=1e6])=>{Game.cookies+=e})),register("gainlumps","Gain N sugar lumps",(([e=100])=>{Game.gainLumps(e)})),register("unlockupgrades","Unlock all upgrades",(()=>{Object.values(Game.UpgradesById).forEach((e=>e.unlock&&e.unlock()))})),register("forceupgrades","Mark all upgrades bought",(()=>{Object.values(Game.UpgradesById).forEach((e=>e.bought=1))})),register("allachievements","Unlock all achievements",(()=>{Object.values(Game.AchievementsById).forEach((e=>Game.Win(e.id)))})),register("reset","Hard-reset the game",(()=>{Game.HardReset(2)})),register("rename","Rename your bakery",(e=>{Game.bakeryName=e.join(" ")+"'s Bakery",Game.RefreshStore()})),
// ─── Autos & Toggles ─────────────────────────────────────
register("autoclick","Toggle auto-click (50ms)",(()=>{toggle("_bc_autoClick",(()=>Game.ClickCookie()),50,"Auto-click")})),register("autobuy","Toggle auto-buy buildings (500ms)",(()=>{toggle("_bc_autoBuy",(()=>{Object.values(Game.ObjectsById).forEach((e=>e.buy(1)))}),500,"Auto-buy")})),register("autoupgrade","Toggle auto-buy upgrades (1s)",(()=>{toggle("_bc_autoUpg",(()=>{Game.UpgradesInStore.forEach((e=>e.buy()))}),1e3,"Auto-upgrade")})),register("autoascend","Toggle auto-ascend when prestige+1 ready (2s)",(()=>{toggle("_bc_autoAscend",(()=>{const e=Math.floor(Game.prestige)+1;Game.HowMuchPrestige(Game.cookiesEarned)>=e&&(Game.Ascend(),console.log("🔁 Ascended"))}),2e3,"Auto-Ascend")})),
// ─── Buffs & Golden Cookies ───────────────────────────────
register("frenzy","Activate Frenzy (36s)",(()=>{Game.AddBuff("frenzy",36*Game.fps)})),register("elderfrenzy","Activate Elder Frenzy (36s)",(()=>{Game.AddBuff("elderFrenzy",36*Game.fps)})),register("clickfrenzy","Activate Click Frenzy (36s)",(()=>{Game.AddBuff("clickFrenzy",36*Game.fps)})),register("goldenrain","Spawn 20 golden cookies",(()=>{for(let e=0;e<20;e++)new Game.shimmer("golden")})),register("lucky","Spawn a Lucky golden cookie",(()=>{new Game.shimmer("golden",Game.mouseX,Game.mouseY,"lucky")})),register("ruin","Spawn a Ruin golden cookie",(()=>{new Game.shimmer("golden",Game.mouseX,Game.mouseY,"ruin")})),register("chain","Spawn a Cookie Chain golden cookie",(()=>{new Game.shimmer("golden",Game.mouseX,Game.mouseY,"chain")})),register("storm","Spawn a Cookie Storm golden cookie",(()=>{new Game.shimmer("golden",Game.mouseX,Game.mouseY,"cookie storm")})),
// ─── Buildings & Economy ─────────────────────────────────
register("buycheapest","Buy the cheapest building",(()=>{const e=Object.values(Game.ObjectsById).sort(((e,o)=>e.getPrice()-o.getPrice()))[0];Game.cookies>=e.getPrice()&&e.buy(1)})),register("sellall","Sell all buildings",(()=>{Object.values(Game.ObjectsById).forEach((e=>e.sell(e.amount)))})),register("cheapbuilds","Set all base prices to 1",(()=>{Object.values(Game.ObjectsById).forEach((e=>e.basePrice=1))})),
// ─── Stats & Debug ────────────────────────────────────────
register("stats","Show cookies, CPS, buildings, upgrades",(()=>{console.table({Cookies:Game.cookies,CPS:Game.cookiesPs,Buildings:Object.values(Game.ObjectsById).reduce(((e,o)=>e+o.amount),0),Upgrades:Object.values(Game.UpgradesById).filter((e=>e.bought)).length})})),register("lifetime","Show lifetime stats",(()=>{console.table({Earned:Game.cookiesEarned,Prestige:Game.prestige,Chips:Game.heavenlyChips,Resets:Game.resets})})),register("listbld","List buildings & counts",(()=>{Object.values(Game.ObjectsById).forEach((e=>console.log(`${e.name}: ${e.amount}`)))})),register("listupg","List owned upgrades",(()=>{Object.values(Game.UpgradesById).filter((e=>e.bought)).forEach((e=>console.log(e.name)))})),
// ─── Seasonal & Misc ──────────────────────────────────────
register("season","Set season (christmas/halloween/valentines)",(([e=""])=>{Game.season=e,Game.computeSeasonPrices(),Game.refreshSeason()})),register("cultivation","Toggle Garden UI",(()=>{Game.ToggleGarden()})),register("debug","Open debug menu",(()=>{Game.OpenSesame()})),register("bg","Set page background color",(([e=""])=>{document.body.style.background=e})),
// Expose only burntCookie
window.burntCookie=function run(o){if(!o)return showHelp();const[s,...a]=o.trim().split(/\s+/),r=s.toLowerCase(),t=a.map((e=>isNaN(e)?e:parseFloat(e)));if("help"===r)return showHelp();const n=e[r];if(!n)return console.warn(`❌ Unknown command: ${r}`),showHelp();try{n.fn(t),console.log(`✅ ${r}`,...t)}catch(e){console.error(`🔥 Error in ${r}:`,e)}},console.log("%c🔥 Burnt Cookie V10 🍪 is ready!","color:orange;font-weight:bold"),console.log("Use: %cburntCookie('help')","color:green;font-height:bold")}();
